version: "3.7"
services:
  web:
    image: ${REPO}/${CONTAINER}:${TAG}
    container_name: ${CONTAINER}
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ~/volumes/vote:/usr/src/app/logs
      - ~/etc/timezone:/etc/localtime:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - ${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx