version: "3.7"
services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: customized
    environment:
      - TZ=Asia/Taipei
    volumes:
      # - ~/volumes/data_for_KG:/usr/src/app/data_for_KG
      - ~/volumes/customized:/usr/src/app/logs
      - ~/etc/timezone:/etc/localtime:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    restart: always
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - ${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s